version: 2.1

orbs:
 android: circleci/android@0.2.0

jobs:
  build:
    executor: android/android
        
    steps:
      - checkout
      - run:
          name: chmod permissions
          command: chmod +x ./gradlew
      - run:
          command: ./gradlew build
      - store_artifacts:
          path: app/build/outputs/apk/
          destination: apks/
